[tool.poetry]
name = "job"
version = "0.1.0"
description = ""
authors = ["Jason Forte <hello@jforte.me>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
psutil = "^6.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
